// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzihzqsmpiwsuwrgzvqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6aWh6cXNtcGl3c3V3cmd6dnFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjI3ODMsImV4cCI6MjA1NjkzODc4M30.9g4Q7afQCOjyv0NULEjL7yVKevOw4QvyQ6YmPN1rPSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);